import = ["~/.config/alacritty/catppuccin-macchiato.toml"]

[font]
size = 11.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
opacity = 0.75
blur = true
dimensions = { columns = 225, lines = 53 }
decorations_theme_variant = "Dark"

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
  { key = "Return", mods = "Control|Shift", action = "ToggleMaximized" },
  { key = "K", mods = "Control|Shift", action = "ScrollPageUp" },
  { key = "J", mods = "Control|Shift", action = "ScrollPageDown" },
]
