import = ["~/.config/alacritty/catppuccin-macchiato.toml"]

[font]
size = 10.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
opacity = 0.75
blur = true

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
  { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
]
